# Generated by Django 5.2.1 on 2026-05-06 22:51

import aranha_estetica.models.anamnese
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0022_tag_cliente_foto_url_cliente_indicado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioanamnese',
            name='modalidade',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='formularioanamnese',
            name='tipo',
            field=models.CharField(choices=[('ANAMNESE', 'Anamnese pre-atendimento'), ('PESQUISA', 'Pesquisa pos-atendimento')], db_index=True, default='ANAMNESE', max_length=12),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='link_videoconferencia',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='modalidade',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ONLINE', 'Online'), ('HIBRIDO', 'Híbrido (presencial + online)')], db_index=True, default='PRESENCIAL', max_length=12),
        ),
        migrations.AddField(
            model_name='respostaanamnese',
            name='respondida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respostaanamnese',
            name='token',
            field=models.CharField(db_index=True, default=aranha_estetica.models.anamnese._gen_resposta_token, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='formularioanamnese',
            name='escopo',
            field=models.CharField(choices=[('GLOBAL', 'Global (todo agendamento)'), ('CATEGORIA', 'Por categoria de procedimento'), ('PROCEDIMENTO', 'Por procedimento especifico'), ('MODALIDADE', 'Por modalidade (presencial/online/hibrido)')], default='GLOBAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='formularioanamnese',
            index=models.Index(fields=['ativo', 'tipo'], name='idx_anamnese_ativo_tipo'),
        ),
        migrations.AddIndex(
            model_name='respostaanamnese',
            index=models.Index(fields=['respondida_em'], name='idx_anamnese_resp_data'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('modalidade__in', ['PRESENCIAL', 'ONLINE', 'HIBRIDO'])), name='chk_procedimento_modalidade'),
        ),
    ]
