# Generated by Django 5.2.1 on 2026-05-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0023_modalidade_pesquisa_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('LEMBRETE', 'Lembrete D-1'), ('LEMBRETE_2H', 'Lembrete T-2h'), ('CONFIRMACAO', 'Confirmação'), ('CANCELAMENTO', 'Cancelamento'), ('NPS', 'Pesquisa NPS'), ('PESQUISA', 'Pesquisa de satisfação detalhada'), ('APROVACAO', 'Aprovação Profissional')], default='LEMBRETE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='idx_cliente_email'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('deletado_em__isnull', True), models.Q(('email__isnull', True), _negated=True), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_cliente_email_ativo'),
        ),
    ]
