# Generated by Django 5.2.1 on 2026-05-08 03:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0024_cliente_email_index_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGA', 'Paga'), ('ESTORNADA', 'Estornada')], default='PENDENTE', max_length=15)),
                ('pago_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimento_comissao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegraComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('percentual', models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 30.00 para 30%. Se preenchido, valor_fixo deve ser nulo.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_fixo', models.DecimalField(blank=True, decimal_places=2, help_text='Valor fixo R$. Se preenchido, percentual deve ser nulo.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'regra_comissao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='atendimento_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retornos', to='aranha_estetica.atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='is_retorno',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_indicacao',
            field=models.CharField(blank=True, db_index=True, help_text='Codigo curto compartilhavel (ex: A1B2C3D4) gerado automaticamente.', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='duracao_retorno_minutos',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='prazo_retorno_max_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='prazo_retorno_min_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='requer_retorno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movimentocredito',
            name='origem',
            field=models.CharField(choices=[('VALE_PRESENTE', 'Vale presente'), ('CANCELAMENTO', 'Refund cancelamento'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('USO_AGENDAMENTO', 'Uso em agendamento'), ('CASHBACK_INDICACAO', 'Cashback por indicacao'), ('CASHBACK_ESTORNO', 'Estorno cashback'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
        migrations.AddIndex(
            model_name='movimentocredito',
            index=models.Index(fields=['origem', 'tipo'], name='idx_movcred_origem_tipo'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('is_retorno', False), ('atendimento_origem__isnull', False), _connector='OR'), name='chk_retorno_tem_origem'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('is_retorno', False), ('valor_cobrado', 0), ('valor_cobrado__isnull', True), _connector='OR'), name='chk_retorno_valor_zero'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.CheckConstraint(condition=models.Q(('indicado_por_id', models.F('id')), _negated=True), name='chk_cliente_nao_indica_si_mesmo'),
        ),
        migrations.AddConstraint(
            model_name='movimentocredito',
            constraint=models.UniqueConstraint(condition=models.Q(('origem', 'CASHBACK_INDICACAO')), fields=('credito', 'atendimento'), name='uniq_cashback_indicacao_por_atendimento'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('requer_retorno', False), models.Q(('prazo_retorno_max_dias__isnull', False), ('prazo_retorno_min_dias__isnull', False)), _connector='OR'), name='chk_procedimento_prazo_retorno_coerente'),
        ),
        migrations.AddField(
            model_name='movimentocomissao',
            name='atendimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='aranha_estetica.atendimento'),
        ),
        migrations.AddField(
            model_name='movimentocomissao',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes', to='aranha_estetica.profissional'),
        ),
        migrations.AddField(
            model_name='regracomissao',
            name='procedimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to='aranha_estetica.procedimento'),
        ),
        migrations.AddField(
            model_name='regracomissao',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regras_comissao', to='aranha_estetica.profissional'),
        ),
        migrations.AddField(
            model_name='movimentocomissao',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aranha_estetica.regracomissao'),
        ),
        migrations.AddIndex(
            model_name='regracomissao',
            index=models.Index(fields=['profissional', 'procedimento', 'ativo'], name='idx_regra_comissao_lookup'),
        ),
        migrations.AddConstraint(
            model_name='regracomissao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percentual__isnull', False), ('valor_fixo__isnull', True)), models.Q(('percentual__isnull', True), ('valor_fixo__isnull', False)), _connector='OR'), name='chk_regra_comissao_percentual_xor_fixo'),
        ),
        migrations.AddIndex(
            model_name='movimentocomissao',
            index=models.Index(fields=['profissional', 'status'], name='idx_comissao_prof_status'),
        ),
        migrations.AddIndex(
            model_name='movimentocomissao',
            index=models.Index(fields=['-criado_em'], name='idx_comissao_criado'),
        ),
        migrations.AddConstraint(
            model_name='movimentocomissao',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDENTE', 'PAGA'])), fields=('atendimento',), name='uniq_comissao_ativa_por_atendimento'),
        ),
    ]
