# Generated by Django 5.2.1 on 2026-06-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0027_remodelagem_fase1a_corta_mortas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CodigoVerificacao',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='proposito',
            field=models.CharField(choices=[('AGENDAMENTO', 'Agendamento'), ('LOGIN_CLIENTE', 'Login cliente'), ('DSAR', 'Export de dados LGPD')], default='AGENDAMENTO', max_length=20),
        ),
    ]
