# Generated by Django 5.2.1 on 2026-06-11 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0029_remodelagem_fase1c_papel_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowExecucao',
        ),
        migrations.DeleteModel(
            name='WorkflowRegra',
        ),
    ]
