# Generated by Django 5.2.1 on 2026-06-12 00:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0030_remodelagem_fase1d_remove_workflow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimento',
            name='chk_retorno_tem_origem',
        ),
        migrations.RemoveConstraint(
            model_name='atendimento',
            name='chk_retorno_valor_zero',
        ),
        migrations.RemoveConstraint(
            model_name='procedimento',
            name='chk_procedimento_prazo_retorno_coerente',
        ),
        migrations.RemoveConstraint(
            model_name='regracomissao',
            name='chk_regra_comissao_percentual_xor_fixo',
        ),
        migrations.RemoveIndex(
            model_name='logauditoria',
            name='idx_auditoria_tabela',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='idx_notificacao_tipo_status',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='idx_notif_nps_lookup',
        ),
        migrations.RenameField(
            model_name='anotacaosessao',
            old_name='usuario',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='is_retorno',
            new_name='eh_retorno',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='consent_email_marketing_at',
            new_name='consent_email_marketing_em',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='consent_whatsapp_confirmacao_at',
            new_name='consent_whatsapp_confirmacao_em',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='consent_whatsapp_nps_at',
            new_name='consent_whatsapp_nps_em',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='unsubscribe_token',
            new_name='token_descadastro',
        ),
        migrations.RenameField(
            model_name='logauditoria',
            old_name='id_registro_afetado',
            new_name='registro_id',
        ),
        migrations.RenameField(
            model_name='logauditoria',
            old_name='tabela_afetada',
            new_name='tabela',
        ),
        migrations.RenameField(
            model_name='movimentocredito',
            old_name='saldo_apos',
            new_name='saldo_resultante',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='resposta_cliente',
            new_name='resposta',
        ),
        migrations.RenameField(
            model_name='notificacao',
            old_name='status_envio',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='procedimento',
            old_name='requer_retorno',
            new_name='exige_retorno',
        ),
        migrations.RenameField(
            model_name='procedimento',
            old_name='prazo_retorno_max_dias',
            new_name='retorno_maximo_dias',
        ),
        migrations.RenameField(
            model_name='procedimento',
            old_name='prazo_retorno_min_dias',
            new_name='retorno_minimo_dias',
        ),
        migrations.RenameField(
            model_name='regracomissao',
            old_name='valor_fixo',
            new_name='valor',
        ),
        migrations.AlterField(
            model_name='regracomissao',
            name='percentual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ex: 30.00 para 30%. Se preenchido, valor deve ser nulo.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tabela'], name='idx_auditoria_tabela'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'status'], name='idx_notificacao_tipo_status'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'canal', 'status', '-criado_em'], name='idx_notif_nps_lookup'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('eh_retorno', False), ('atendimento_origem__isnull', False), _connector='OR'), name='chk_retorno_tem_origem'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('eh_retorno', False), ('valor_cobrado', 0), ('valor_cobrado__isnull', True), _connector='OR'), name='chk_retorno_valor_zero'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('exige_retorno', False), models.Q(('retorno_maximo_dias__isnull', False), ('retorno_minimo_dias__isnull', False)), _connector='OR'), name='chk_procedimento_prazo_retorno_coerente'),
        ),
        migrations.AddConstraint(
            model_name='regracomissao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('percentual__isnull', False), ('valor__isnull', True)), models.Q(('percentual__isnull', True), ('valor__isnull', False)), _connector='OR'), name='chk_regra_comissao_percentual_xor_fixo'),
        ),
    ]
