# Generated by Django 5.2.1 on 2026-06-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aranha_estetica', '0032_remodelagem_fase2b_renames_tabelas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cliente',
            name='idx_cliente_nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome_completo',
            new_name='nome',
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='idx_cliente_nome'),
        ),
    ]
