# Generated by Django 5.2.1 on 2026-03-19 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(db_column='senha_hash', max_length=255)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id_atendimento', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('valor_cobrado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status_atendimento', models.CharField(default='AGENDADO', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atendimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoVerificacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefone', models.CharField(max_length=20)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'codigo_verificacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Funcionalidade',
            fields=[
                ('id_funcionalidade', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'funcionalidade',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfil',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id_procedimento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'procedimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id_profissional', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'profissional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioPergunta',
            fields=[
                ('id_pergunta', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo_resposta', models.CharField(max_length=50)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prontuario_pergunta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoNPS',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.atendimento')),
            ],
            options={
                'db_table': 'avaliacao_nps',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.cliente'),
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('acao', models.CharField(max_length=255)),
                ('tabela_afetada', models.CharField(blank=True, max_length=100, null=True)),
                ('id_registro_afetado', models.IntegerField(blank=True, null=True)),
                ('detalhes', models.JSONField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'log_auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id_notificacao', models.AutoField(primary_key=True, serialize=False)),
                ('canal', models.CharField(max_length=20)),
                ('status_envio', models.CharField(max_length=20)),
                ('data_hora_envio', models.DateTimeField(blank=True, null=True)),
                ('atendimento', models.ForeignKey(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.atendimento')),
            ],
            options={
                'db_table': 'notificacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PacoteCliente',
            fields=[
                ('id_pacote_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_comprados', to='app_shivazen.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.pacote')),
            ],
            options={
                'db_table': 'pacote_cliente',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='id_perfil', null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.perfil'),
        ),
        migrations.CreateModel(
            name='PerfilFuncionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionalidade', models.ForeignKey(db_column='id_funcionalidade', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.funcionalidade')),
                ('perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.perfil')),
            ],
            options={
                'db_table': 'perfil_funcionalidade',
                'managed': True,
                'unique_together': {('perfil', 'funcionalidade')},
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='funcionalidades',
            field=models.ManyToManyField(through='app_shivazen.PerfilFuncionalidade', to='app_shivazen.funcionalidade'),
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('sessoes', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tratamento_estetico_anterior', models.TextField(blank=True, null=True, verbose_name='Realizou algum tratamento estético? Se sim, qual?')),
                ('doenca_pele', models.TextField(blank=True, null=True, verbose_name='Possui doença de pele (psoríase, vitiligo, dermatites, lúpus)?')),
                ('tratamento_cancer', models.TextField(blank=True, null=True, verbose_name='Está em tratamento de câncer ou fez tratamento há menos de 5 anos?')),
                ('melasma_pintas', models.TextField(blank=True, null=True, verbose_name='Tem melasma ou pintas mais pigmentadas? Se sim, em qual local?')),
                ('uso_acido', models.TextField(blank=True, null=True, verbose_name='Utiliza algum tipo de ácido?')),
                ('medicacao_continua', models.TextField(blank=True, null=True, verbose_name='Toma alguma medicação contínua?')),
                ('gravida_amamentando', models.TextField(blank=True, null=True, verbose_name='Está grávida ou amamentando?')),
                ('alergia', models.TextField(blank=True, null=True, verbose_name='Tem alergia a algum medicamento ou alimento? Se sim, qual?')),
                ('implante_marcapasso', models.TextField(blank=True, null=True, verbose_name='Tem algum implante, marcapasso ou prótese de metal?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.procedimento')),
            ],
            options={
                'db_table': 'orcamento',
                'ordering': ['-data_criacao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id_item_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_sessoes', models.IntegerField(default=1)),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_shivazen.pacote')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
            ],
            options={
                'db_table': 'item_pacote',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='procedimento',
            field=models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.procedimento'),
        ),
        migrations.CreateModel(
            name='Preco',
            fields=[
                ('id_preco', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
                ('profissional', models.ForeignKey(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'preco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id_lista_espera', models.AutoField(primary_key=True, serialize=False)),
                ('data_desejada', models.DateField()),
                ('turno_desejado', models.CharField(blank=True, max_length=20, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.cliente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
                ('profissional_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'lista_espera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DisponibilidadeProfissional',
            fields=[
                ('id_disponibilidade', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('profissional', models.ForeignKey(db_column='id_profissional', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'disponibilidade_profissional',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id_bloqueio', models.AutoField(primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('profissional', models.ForeignKey(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'bloqueio_agenda',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='atendimento',
            name='profissional',
            field=models.ForeignKey(db_column='id_profissional', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.profissional'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='profissional',
            field=models.OneToOneField(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shivazen.profissional'),
        ),
        migrations.CreateModel(
            name='ProfissionalProcedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
                ('profissional', models.ForeignKey(db_column='id_profissional', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'profissional_procedimento',
                'managed': True,
                'unique_together': {('profissional', 'procedimento')},
            },
        ),
        migrations.AddField(
            model_name='procedimento',
            name='profissionais',
            field=models.ManyToManyField(through='app_shivazen.ProfissionalProcedimento', to='app_shivazen.profissional'),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id_promocao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('ativa', models.BooleanField(default=True)),
                ('imagem_url', models.CharField(blank=True, max_length=500, null=True)),
                ('procedimento', models.ForeignKey(blank=True, db_column='id_procedimento', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
            ],
            options={
                'db_table': 'promocao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id_prontuario', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.OneToOneField(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.cliente')),
            ],
            options={
                'db_table': 'prontuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProntuarioResposta',
            fields=[
                ('id_resposta', models.AutoField(primary_key=True, serialize=False)),
                ('resposta_texto', models.TextField(blank=True, null=True)),
                ('resposta_boolean', models.BooleanField(blank=True, null=True)),
                ('atendimento', models.ForeignKey(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.atendimento')),
                ('pergunta', models.ForeignKey(db_column='id_pergunta', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.prontuariopergunta')),
            ],
            options={
                'db_table': 'prontuario_resposta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessaoPacote',
            fields=[
                ('id_sessao_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('data_debito', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sessao_pacote_vinculada', to='app_shivazen.atendimento')),
                ('pacote_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_realizadas', to='app_shivazen.pacotecliente')),
            ],
            options={
                'db_table': 'sessao_pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TermoConsentimento',
            fields=[
                ('id_termo', models.AutoField(primary_key=True, serialize=False)),
                ('ip_assinatura', models.CharField(blank=True, max_length=45, null=True)),
                ('data_hora_assinatura', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(db_column='id_atendimento', on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.atendimento')),
                ('usuario_assinatura', models.ForeignKey(blank=True, db_column='id_usuario_assinatura', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'termo_consentimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokenGoogleAgenda',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'token_google_agenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('sessoes', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='vendas', to='app_shivazen.cliente')),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.procedimento')),
                ('profissional', models.ForeignKey(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'venda',
                'ordering': ['-data'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetaProfissional',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'meta_profissional',
                'managed': True,
                'unique_together': {('profissional', 'mes', 'ano')},
            },
        ),
    ]
