# Generated by Django 5.2.1 on 2026-04-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['status'], name='idx_atendimento_status'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['data_hora_inicio'], name='idx_atendimento_data'),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['cliente', 'status'], name='idx_atendimento_cli_status'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefone'], name='idx_cliente_telefone'),
        ),
    ]
