# Generated by Django 5.2.1 on 2026-03-12 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0002_codigoverificacao_alter_atendimento_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoNPS',
            fields=[
                ('id_avaliacao', models.AutoField(primary_key=True, serialize=False)),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.atendimento')),
            ],
            options={
                'db_table': 'avaliacao_nps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaEspera',
            fields=[
                ('id_lista_espera', models.AutoField(primary_key=True, serialize=False)),
                ('data_desejada', models.DateField()),
                ('turno_desejado', models.CharField(blank=True, max_length=20, null=True)),
                ('notificado', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.cliente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
                ('profissional_desejado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'lista_espera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemPacote',
            fields=[
                ('id_item_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade_sessoes', models.IntegerField(default=1)),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.procedimento')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_shivazen.pacote')),
            ],
            options={
                'db_table': 'item_pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PacoteCliente',
            fields=[
                ('id_pacote_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='ATIVO', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_comprados', to='app_shivazen.cliente')),
                ('pacote', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.pacote')),
            ],
            options={
                'db_table': 'pacote_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SessaoPacote',
            fields=[
                ('id_sessao_pacote', models.AutoField(primary_key=True, serialize=False)),
                ('data_debito', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='sessao_pacote_vinculada', to='app_shivazen.atendimento')),
                ('pacote_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_realizadas', to='app_shivazen.pacotecliente')),
            ],
            options={
                'db_table': 'sessao_pacote',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TokenGoogleAgenda',
            fields=[
                ('id_token', models.AutoField(primary_key=True, serialize=False)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'token_google_agenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetaProfissional',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('valor_meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'meta_profissional',
                'managed': True,
                'unique_together': {('profissional', 'mes', 'ano')},
            },
        ),
    ]
