# Generated by Django 5.2.1 on 2026-03-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0002_notificacao_data_hora_resposta_notificacao_mensagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
