# Generated by Django 5.2.1 on 2026-03-19 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0003_pacote_avaliacaonps_listaespera_itempacote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id_orcamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('endereco_cep', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('sessoes', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('tratamento_estetico_anterior', models.TextField(blank=True, null=True, verbose_name='Realizou algum tratamento estético? Se sim, qual?')),
                ('doenca_pele', models.TextField(blank=True, null=True, verbose_name='Possui doença de pele (psoríase, vitiligo, dermatites, lúpus)?')),
                ('tratamento_cancer', models.TextField(blank=True, null=True, verbose_name='Está em tratamento de câncer ou fez tratamento há menos de 5 anos?')),
                ('melasma_pintas', models.TextField(blank=True, null=True, verbose_name='Tem melasma ou pintas mais pigmentadas? Se sim, em qual local?')),
                ('uso_acido', models.TextField(blank=True, null=True, verbose_name='Utiliza algum tipo de ácido?')),
                ('medicacao_continua', models.TextField(blank=True, null=True, verbose_name='Toma alguma medicação contínua?')),
                ('gravida_amamentando', models.TextField(blank=True, null=True, verbose_name='Está grávida ou amamentando?')),
                ('alergia', models.TextField(blank=True, null=True, verbose_name='Tem alergia a algum medicamento ou alimento? Se sim, qual?')),
                ('implante_marcapasso', models.TextField(blank=True, null=True, verbose_name='Tem algum implante, marcapasso ou prótese de metal?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.procedimento')),
            ],
            options={
                'db_table': 'orcamento',
                'ordering': ['-data_criacao'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('sessoes', models.IntegerField(default=1)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='vendas', to='app_shivazen.cliente')),
                ('procedimento', models.ForeignKey(db_column='id_procedimento', on_delete=django.db.models.deletion.RESTRICT, to='app_shivazen.procedimento')),
                ('profissional', models.ForeignKey(blank=True, db_column='id_profissional', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shivazen.profissional')),
            ],
            options={
                'db_table': 'venda',
                'ordering': ['-data'],
                'managed': True,
            },
        ),
    ]
