# Generated by Django 5.2.1 on 2026-03-29 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0003_produto_data_validade_produto_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AlterUniqueTogether(
            name='metaprofissional',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='metaprofissional',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='movimentacaoestoque',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='orcamento',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='tokengoogleagenda',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='procedimento',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='profissional',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='descricao_preco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='promocao',
            field=models.ForeignKey(blank=True, db_column='id_promocao', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_shivazen.promocao'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='reagendado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagendamentos', to='app_shivazen.atendimento'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='valor_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='avaliacaonps',
            name='alerta_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceite_termos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_aceite_termos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='faltas_consecutivas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ip_aceite_termos',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listaespera',
            name='token_reserva',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='pacote',
            name='validade_meses',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='pacotecliente',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CategoriaProduto',
        ),
        migrations.DeleteModel(
            name='MetaProfissional',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='MovimentacaoEstoque',
        ),
        migrations.DeleteModel(
            name='Orcamento',
        ),
        migrations.DeleteModel(
            name='TokenGoogleAgenda',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
