# Generated by Django 5.2.1 on 2026-04-15 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0005_add_procedimento_slug_imagem'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='atendimento',
            name='chk_atendimento_status',
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('CONFIRMADO', 'Confirmado'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado'), ('FALTOU', 'Faltou'), ('REAGENDADO', 'Reagendado')], default='AGENDADO', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['AGENDADO', 'CONFIRMADO', 'REALIZADO', 'CANCELADO', 'FALTOU', 'REAGENDADO'])), name='chk_atendimento_status'),
        ),
    ]
