# Generated by Django 5.2.1 on 2026-04-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='atendimento',
            name='idx_atn_prof_data',
        ),
        migrations.RemoveIndex(
            model_name='notificacao',
            name='idx_notif_atn_status',
        ),
        migrations.RemoveIndex(
            model_name='procedimento',
            name='idx_proc_ativo_cat',
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['tabela_afetada'], name='idx_auditoria_tabela'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['-criado_em'], name='idx_auditoria_criado'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'status_envio'], name='idx_notificacao_tipo_status'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['-criado_em'], name='idx_notificacao_criado'),
        ),
        migrations.AddIndex(
            model_name='pacotecliente',
            index=models.Index(fields=['cliente', 'status'], name='idx_pacote_cli_status'),
        ),
        migrations.AddIndex(
            model_name='preco',
            index=models.Index(fields=['procedimento', 'profissional', '-vigente_desde'], name='idx_preco_lookup'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['ativo'], name='idx_procedimento_ativo'),
        ),
        migrations.AddIndex(
            model_name='procedimento',
            index=models.Index(fields=['categoria'], name='idx_procedimento_categoria'),
        ),
        migrations.AddIndex(
            model_name='profissional',
            index=models.Index(fields=['ativo'], name='idx_profissional_ativo'),
        ),
        migrations.AddIndex(
            model_name='promocao',
            index=models.Index(fields=['ativa', 'data_inicio', 'data_fim'], name='idx_promocao_vigente'),
        ),
        migrations.AddConstraint(
            model_name='bloqueioagenda',
            constraint=models.CheckConstraint(condition=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='chk_bloqueio_fim_maior_inicio'),
        ),
        migrations.AddConstraint(
            model_name='itempacote',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade_sessoes__gt', 0)), name='chk_item_pacote_qtd_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pacote',
            constraint=models.CheckConstraint(condition=models.Q(('preco_total__gte', 0)), name='chk_pacote_preco_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pacote',
            constraint=models.CheckConstraint(condition=models.Q(('validade_meses__gt', 0)), name='chk_pacote_validade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='preco',
            constraint=models.CheckConstraint(condition=models.Q(('valor__gte', 0)), name='chk_preco_valor_positivo'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('duracao_minutos__gt', 0)), name='chk_procedimento_duracao_positiva'),
        ),
        migrations.AddConstraint(
            model_name='procedimento',
            constraint=models.CheckConstraint(condition=models.Q(('categoria__in', ['FACIAL', 'CORPORAL', 'CAPILAR', 'OUTRO'])), name='chk_procedimento_categoria'),
        ),
        migrations.AddConstraint(
            model_name='promocao',
            constraint=models.CheckConstraint(condition=models.Q(('data_fim__gte', models.F('data_inicio'))), name='chk_promocao_data_fim_valida'),
        ),
    ]
