# Generated by Django 5.2.1 on 2026-04-17 14:23

import app_shivazen.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0009_add_pendente_status_and_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='aceita_comunicacao',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='deletado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='unsubscribe_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='ip_origem',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='token_cancelamento',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='valor_cobrado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='valor_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[app_shivazen.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, validators=[app_shivazen.validators.validate_data_nascimento]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='faltas_consecutivas',
            field=models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[app_shivazen.validators.validate_telefone_br]),
        ),
        migrations.AddIndex(
            model_name='atendimento',
            index=models.Index(fields=['profissional', 'data_hora_inicio'], name='idx_atend_prof_data'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome_completo'], name='idx_cliente_nome'),
        ),
        migrations.AddIndex(
            model_name='logauditoria',
            index=models.Index(fields=['usuario', '-criado_em'], name='idx_auditoria_user_data'),
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.CheckConstraint(condition=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='chk_atendimento_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadeprofissional',
            constraint=models.CheckConstraint(condition=models.Q(('hora_fim__gt', models.F('hora_inicio'))), name='chk_disponibilidade_hora_fim_apos_inicio'),
        ),
        migrations.AddConstraint(
            model_name='disponibilidadeprofissional',
            constraint=models.UniqueConstraint(fields=('profissional', 'dia_semana', 'hora_inicio'), name='uniq_disponibilidade_prof_dia_hora'),
        ),
    ]
