# Generated by Django 5.2.1 on 2026-04-17 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0010_atendimento_atualizado_em_cliente_aceita_comunicacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo_hash', models.CharField(max_length=64)),
                ('proposito', models.CharField(choices=[('AGENDAMENTO', 'Agendamento'), ('LOGIN_CLIENTE', 'Login cliente')], default='AGENDAMENTO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('tentativas', models.PositiveSmallIntegerField(default=0)),
                ('ip_origem', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'otp_code',
                'managed': True,
                'indexes': [models.Index(fields=['email', '-criado_em'], name='idx_otp_email_data'), models.Index(fields=['proposito', '-criado_em'], name='idx_otp_prop_data')],
            },
        ),
    ]
