# Generated by Django 5.2.1 on 2026-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0015_otpcode_canal'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['tipo', 'canal', 'status_envio', '-criado_em'], name='idx_notif_nps_lookup'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['atendimento', 'tipo'], name='idx_notif_atend_tipo'),
        ),
    ]
