# Generated by Django 5.2.1 on 2026-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shivazen', '0016_add_notif_nps_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='consent_whatsapp_confirmacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consent_whatsapp_confirmacao_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='consent_whatsapp_confirmacao_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
